all: thistogram phistogram
	gcc thistogram.c -o thistogram -lpthread
	gcc phistogram.c -o phistogram 
thistogram: thistogram.c
	gcc thistogram.c -o thistogram -lpthread
phistogram: phistogram.c
	gcc phistogram.c -o phistogram 
